import Vue from 'vue'
import { Button, Menu, MenuItem, Submenu, Aside, RadioButton, RadioGroup, Container, Header, MenuItemGroup, Main, Table, TableColumn, Message, Card, Dialog, Form, FormItem, Input, Tag, Select, Option, Pagination, Image, Steps, Step, Radio, Alert, Loading, Breadcrumb, BreadcrumbItem, Upload } from 'element-ui'

Vue.use(Button)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Aside)
Vue.use(RadioButton)
Vue.use(RadioGroup)
Vue.use(Container)
Vue.use(Header)
Vue.use(MenuItemGroup)
Vue.use(Main)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Dialog)
Vue.use(Input)
Vue.use(Tag)
Vue.use(Select)
Vue.use(Option)
Vue.use(Pagination)
Vue.use(Image)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Radio)
Vue.use(Alert)
Vue.use(Loading)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Upload)
Vue.prototype.$message = Message
